name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/mizdebsk/javapackages-bootstrap-ci:latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Ensure patches have Forwarded tag
        run: "! grep -L ^Forwarded: patches/*/*.patch | grep ."
      - name: Import cached upstream sources
        run: cp -R /var/cache/upstream .
      - name: Fetch latest upstream sources
        run: ./downstream.sh clone
      - name: Prepare downstream sources
        run: ./downstream.sh prep
      - name: Run build
        run: ./mbi.sh build
      - name: Run dist
        run: ./mbi.sh dist
